In [20]:
import pandas as pd

In [51]:
df = pd.read_parquet(f"../datasets/raw/raw_mmlu_pro.parquet")

In [52]:
df.head(20)

,question_id,question,options,answer,answer_index,cot_content,category,src
0,70,"Typical advertising regulatory bodies suggest,...","[Safe practices, Fear, Jealousy, Trivial, Unsa...",I,8,,business,ori_mmlu-business_ethics
1,71,Managers are entrusted to run the company in t...,"[Shareholders, Diligence, Self-interest, Share...",F,5,,business,ori_mmlu-business_ethics
2,72,There are two main issues associated with ____...,"[Down, Autonomy, Remuneration, Benefit, Down, ...",J,9,,business,ori_mmlu-business_ethics
3,73,_______ locate morality beyond the sphere of r...,"[Ethical egoism, Ethics of duty, Postmodern et...",C,2,,business,ori_mmlu-business_ethics
4,74,Some of key differences between Islamic finan...,"[Interest, Certain, Assured, Both tangible and...",G,6,,business,ori_mmlu-business_ethics
5,75,Which of the following are the three broad gr...,"[Organizational size, industry type, and geogr...",A,0,,business,ori_mmlu-marketing
6,76,Pine and Gilmore (1999) derive four distinct ...,[Customer participation and environmental acqu...,D,3,,business,ori_mmlu-marketing
7,77,Which type of research methods are designed t...,"[Non-probability., Cross-sectional., Qualitati...",J,9,,business,ori_mmlu-marketing
8,78,Where the price is set low relative to the com...,"[Captive product pricing., High-low pricing., ...",E,4,,business,ori_mmlu-marketing
9,79,"Once a train pulls out of a station, or an aer...","[Immeasurability., Impalpability., Variability...",F,5,,business,ori_mmlu-marketing
10,80,A marketing research firm contracts with clien...,"[Data collection firm., Freelance agency., Dat...",E,4,,business,ori_mmlu-marketing
11,81,The six dimensions usually considered to const...,"[Political considerations., Weather conditions...",G,6,,business,ori_mmlu-marketing
12,82,What is the term for the 'rule of thumb' type ...,"[Framing bias, Availability bias, Representati...",J,9,,business,ori_mmlu-management
13,83,As what is ensuring that one individual does n...,"[Work delegation, Workload balancing, Work dis...",D,3,,business,ori_mmlu-management
14,84,What theory is built around the principle that...,"[Social Learning, Contingency, Operant Conditi...",F,5,,business,ori_mmlu-management
15,85,How does lateral communication in an organisat...,[Information is shared only during official me...,J,9,,business,ori_mmlu-management
16,86,The stock of the CCC Corporation is currently ...,"[50.0, 60.0, 55.0, 44.0, 48.0, 53.0, 42.0, 46....",F,5,,business,theoremQA-Finance
17,87,"George is seen to place an even-money $100,000...","[0.525, 0.800, 0.450, 0.575, 0.750, 0.350, 0.6...",A,0,,business,theoremQA-Finance
18,88,Boy Alcott and Jon Buxton are partners in a st...,"[Alcott's share: $3,936, Buxton's share: $4,80...",B,1,,business,stemez-Business
19,89,TheAlforsCompany had a beginning inventory of ...,"[$50,200, $45,100, $60,400, $56,300, $58,800, ...",D,3,,business,stemez-Business

In [53]:
df['options'].iloc[0]

array(['Safe practices, Fear, Jealousy, Trivial',
       'Unsafe practices, Distress, Joy, Trivial',
       'Safe practices, Wants, Jealousy, Trivial',
       'Safe practices, Distress, Fear, Trivial',
       'Unsafe practices, Wants, Jealousy, Serious',
       'Safe practices, Distress, Jealousy, Serious',
       'Safe practices, Wants, Fear, Serious',
       'Unsafe practices, Wants, Fear, Trivial',
       'Unsafe practices, Distress, Fear, Serious'], dtype=object)

In [54]:
df = pd.read_parquet("../results1/unified_baseline/gaia/features_complexity.parquet")

In [56]:
df.head(10)

,overall,task_length,reasoning_depth,tool_dependency,domain_breadth,task_type,complexity_band,query
0,1.780,5.580,1.50,0.0,2.0,2.0,SA,A paper about AI regulation that was originall...
1,2.973,6.652,2.00,2.1,4.0,2.5,MA,I’m researching species that became invasive a...
2,3.297,5.598,6.15,0.0,4.0,1.0,MA,If we assume all articles published by Nature ...
3,3.140,5.251,4.40,1.4,2.0,3.0,MA,"In Unlambda, what exact charcter or text needs..."
4,3.303,6.646,4.40,3.3,0.0,2.0,MA,If Eliud Kipchoge could maintain his record-ma...
5,2.126,5.506,0.50,3.1,0.0,3.0,SA,The attached spreadsheet shows the inventory f...
6,2.126,5.800,2.50,2.0,0.0,1.0,SA,How many studio albums were published by Merce...
7,1.525,5.373,0.50,1.0,2.0,1.0,COT,The object in the British Museum's collection ...
8,1.163,5.444,0.50,0.0,0.0,2.0,LLM,"According to github, when was Regression added..."
9,2.215,9.330,3.05,0.0,0.0,1.0,SA,Here's a fun riddle that I think you'll enjoy....

In [58]:
df['query'].iloc[5]

'The attached spreadsheet shows the inventory for a movie and video game rental store in Seattle, Washington. What is the title of the oldest Blu-Ray recorded in this spreadsheet? Return it as appearing in the spreadsheet.\nAttached file name for reference: 32102e3e-d12a-4209-9163-7b3a104efe5d.xlsx'